# Generated by Django 3.2.6 on 2021-08-31 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=200)),
                ('enddate', models.CharField(max_length=200)),
                ('iscomplete', models.BooleanField(default=False)),
            ],
        ),
    ]
